services:
  backend:
    build: ./backend
    environment:
      - REDIS_URL=redis://redis:6379/0
      - YANDEX_CLOUD_API_KEY
      - YANDEX_CLOUD_FOLDER_ID
    depends_on:
      - redis
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    environment:
      - HF_TOKEN
    depends_on:
      - redis
    ports:
      - "3000:3000"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
